#!/usr/bin/env node

const program = require('commander');
const jsonToGo = require('./lib/json-to-go.js');
const fs = require('fs');
const highlight = require('cli-highlight').highlight;
const chalk = require('chalk');

const error = chalk.bold.red;
const info = chalk.bold.yellow;

let output = function (msg) {
  return  highlight(msg, {language: 'go', ignoreIllegals: true});
}

program
  .name('json-to-go')
  .usage("[Options] [-s/--string] <json-string> [-f/--file] <json-filepath>")
  .version('1.0.0')
  .option('-f, --file <path>', 'location of file containing json to convert')
  .option('-s, --string <string>', 'json string to convert')
  .option('-i, --inline', 'Use inline type definitions')
  .parse(process.argv)

if (program.inline == undefined){program.inline = false};

if (program.file && program.string) {
  return console.log(info('Error: Do not specify both [-s/--string] and [-f/--file]'));
};

if ((program.string == undefined) && (program.file == undefined)) {
  return console.log(info('Error: Must specify one of [-s/--string] or [-f/--file]'));
}

let data = "";

if (program.string) {
  data = program.string;
} else if (program.file) {
  data = fs.readFileSync(program.file, 'utf-8');
} else {
  return console.log( 'No options set' );
};

let result = jsonToGo( data, 'AutoGenerated', program.inline).go;
return console.log( output(result) );
